In [17]:
import os, glob
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [18]:
faceClassifier = cv2.CascadeClassifier('C:/Users/cande/anaconda3/Lib/site-packages/cv2/data/haarcascade_frontalface_default.xml')
img = cv2.imread("Houses/Hufflepuff/777.jpg",0)
img2 = img.copy()

In [19]:
faces =  faceClassifier.detectMultiScale(img)
count = 0

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(128.0,255),2)
    rostro = img2[y:y+h,x:x+w]
    rostro = cv2.resize(rostro,(150,150), interpolation=cv2.INTER_CUBIC)
    cv2.imwrite("rostro_{}.jpg".format(count),rostro)
    count = count+1
    print(count)

    cv2.imshow("rostro",rostro)
    cv2.imshow("image",img)
    cv2.waitKey(1)

1


In [20]:
cv2.destroyAllWindows()

In [21]:
houses = [
    "Gryffindor",
    "Hufflepuff",
    "Slytherin",
    "Ravenclaw"
]

path = "C:/Users/cande/Desktop/Sorting-Hat/Houses/"

for house in houses:
    count = 0
    for img in glob.glob(path+house+"/*"):
        try:
            img = img.replace("\\","/")
            img = cv2.imread(img,0)
            img2= img.copy()
            faces =  faceClassifier.detectMultiScale(img2)

            for (x,y,w,h) in faces:
                cv2.rectangle(img2,(x,y),(x+w,y+h),(128.0,255),2)
                rostro = img2[y:y+h,x:x+w]
                rostro = cv2.resize(rostro,(64,64), interpolation=cv2.INTER_CUBIC)
                cv2.imwrite("{}_{}.jpg".format(house,count),rostro)
                count = count+1
                if count % 10 == 0:
                    print(count)

                cv2.imshow("rostro",rostro)
    #             cv2.imshow("image",img2)
                cv2.waitKey(1)
        except AttributeError:
            print(f"da error {img}")

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
10
20
30
40
50
60
70
80
90
100
110
120
10
20
30
da error None
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150


[[61 61 61 ... 88 88 87]
 [60 60 60 ... 88 88 88]
 [60 60 60 ... 88 88 88]
 ...
 [26 35 36 ... 45 46 46]
 [25 30 57 ... 45 46 47]
 [18 14 53 ... 45 45 46]]
